### ISSUE TITLE
The PalMDB used by Serratus(https://serratus.io/) appears to be different from the one on your Github?

### ISSUE THREAD

**Issue by ZongzhiWu** [rcedgar/palmdb#2]
![image](https://user-images.githubusercontent.com/73645801/151519757-12ff4c0d-9c54-4f3f-b23a-d6f028dcc492.png)
Fig.1
It seems that the taxonomic annotation of 'u184631'  in 'palmID: Viral-RdRP Analysis--https://serratus.io' (Fig.1) is different from that in the PalmDB downloaded from your github.

**Comment by ababaian** [comment]
I'm not sure what I'm looking at here, `palmID` uses the `otu_centroids.fa` file from `palmDB` in 2021-03-14/.

**Comment by ZongzhiWu** [comment]
I used the `named.fa` file to get taxonomic annotations for my RdRP palmprints based on diamond blastp output file. 
I don't know why `palmID` uses the `otu_centroids.fa` file, it seems that the `named.fa` file contains more palmprints sequences.
Besides, I also wonder the best aa-identity cutoff for taxonomic prediction at phylum, family, genus, species and how many top hits should I consider (500 in `palmID` seems too many?), because `palmID` just give a taxonomic-inference pre-report.

**Comment by ZongzhiWu** [comment]
> I'm not sure what I'm looking at here, `palmID` uses the `otu_centroids.fa` file from `palmDB` in 2021-03-14/.

I used the `named.fa` file to get taxonomic annotations for my RdRP palmprints based on diamond blastp output file.
But I don't know why `palmID` uses the `otu_centroids.fa` file, it seems that the `named.fa` file contains more palmprints sequences.
Besides, I also wonder the best aa-identity cutoff for taxonomic prediction at phylum, family, genus, species and how many top hits should I consider (500 in `palmID` seems too many?), because `palmID` just give a taxonomic-inference pre-report.

**Comment by ababaian** [comment]
The centroids are one representative sequence per 90% identity cluster, you can read our [preprint](https://www.biorxiv.org/content/10.1101/2021.03.02.433648v1) which explains the relationship between sOTU and taxonomic species. In short, there is mostly agreement but lots of exceptions. The current implementation is in fact very naive wrt taxonomy but if this is something you think can be significantly improved we're happy to take a hand and/or help direct you in the right direction.

Can you explain what task you are hoping to accomplish and the discrepancy you are seeing between the files exactly?

**Comment by ZongzhiWu** [comment]
> The centroids are one representative sequence per 90% identity cluster, you can read our [preprint](https://www.biorxiv.org/content/10.1101/2021.03.02.433648v1) which explains the relationship between sOTU and taxonomic species. In short, there is mostly agreement but lots of exceptions. The current implementation is in fact very naive wrt taxonomy but if this is something you think can be significantly improved we're happy to take a hand and/or help direct you in the right direction.
> 
> Can you explain what task you are hoping to accomplish and the discrepancy you are seeing between the files exactly?

I have finished identification of palmprints in my metatranscriptomic, and then searched them against the `named.fa` file using `diamond`.
What I want to achieve is to infer the taxonomy of each palmprint at different ranks (phylum, family, genus, species) based on these `diamond` results.
However, I don't know how to choose the aa-identity cutoff and the number of top hits (I saw `palmID` uses the top 500 hits or the top 10 hits?) applicable to taxonomic prediction at different ranks?

**Comment by ababaian** [comment]
So this is not currently implemented, and I really wish it was. Taxonomy is "messy" to have simple classifications, what you can do is measure the distance of your input sequences to named palmprints (which it sounds like that's what you did). Note: the set of named palmprints is probably like 1/10th the genetic diversity compared to all known palmprints. There may be more sequences, but that is because there are more "sub-species" within a given palmprint for the things which are named.

This is already semi-automated if you look at this figure from `palmID` ![Taxa](https://github.com/ababaian/palmid/blob/main/img/waxsys_tax.png). But the transfer of species identifiers from `named.fa` to `otu_centroids.fa` is not perfect.

As for cut-offs, I've used 90% species, 70% genus, 40% family within global palmprint alignments. This is of course an approximation as the definition of species is variable depending on what virus you're looking at. This definition is at the very least internally consistent, no more no less.

**Comment by ZongzhiWu** [comment]
> So this is not currently implemented, and I really wish it was. Taxonomy is "messy" to have simple classifications, what you can do is measure the distance of your input sequences to named palmprints (which it sounds like that's what you did). Note: the set of named palmprints is probably like 1/10th the genetic diversity compared to all known palmprints. There may be more sequences, but that is because there are more "sub-species" within a given palmprint for the things which are named.
> 
> This is already semi-automated if you look at this figure from `palmID` ![Taxa](https://github.com/ababaian/palmid/blob/main/img/waxsys_tax.png). But the transfer of species identifiers from `named.fa` to `otu_centroids.fa` is not perfect.
> 
> As for cut-offs, I've used 90% species, 70% genus, 40% family within global palmprint alignments. This is of course an approximation as the definition of species is variable depending on what virus you're looking at. This definition is at the very least internally consistent, no more no less.

Your suggestions really helps. Thanks a lot!
