### ISSUE TITLE
question about OTU sequences present in otu_centroids.fa with no origin in acc_u.tsv

### ISSUE THREAD

**Issue by katrinakalantar** [rcedgar/palmdb#3]
In following steps similar to the vignette shown here: https://github.com/ababaian/serratus/wiki/Find_novel_viruses_B_palmdb I'm coming across several cases where the OTU identifiers have no origin. I would like to understand more about where these cases come from. 

For example, `u135511` is present in the following files...

```
palmdb/otu_centroids.fa: >u135511
palmdb/u_otu.tsv: u135511	.
palmdb/u_tax.tsv: u135511	Lenarviricota	Allassoviricetes	Levivirales	Leviviridae	.	.
palmdb/uniques.fa: >u135511
``` 

However, does not have an entry in `acc_u.tsv`. 

In particular, how does this differ from an entry such as `u55683` which does have an entry in `acc_u.tsv` indicating origin from a serratus-derived OTU `serratus|v111586`. 

Thank you!

**Comment by rcedgar** [comment]
This appears to be a bug, `u135511` is 100% match to `serratus|v95536` in `serratus.fa` and this should be reflected in `acc_u.tsv`. Thanks for the heads up & apologies for any inconvenience.

**Comment by katrinakalantar** [comment]
Ah, great! Thanks for the clarification. I think there are several more that follow a similar pattern. Is there any way to know these matches from the files that exist already? Or would you suggest gathering this through alignment of the otu_centroids.fa to serratus.fa?

**Comment by rcedgar** [comment]
For sure you should be able to identify sequences from serratus by aligning to serratus.fa, but I didn't dig into the code to figure out how what caused this problem so I'm not 100% sure what's going on. Happy to help in more detail if you can tell me more about what you're really trying to accomplish here.

**Comment by katrinakalantar** [comment]
Totally! I'm basically trying to take a series of contigs that have RdRp palmprints identified through the palmscan tool and then align them to the `otu_centroids.fa` file using DIAMOND. Once I have this information, I'm trying to determine the origin of the closest hits -- i.e. are they more similar to 1. something known in a public repo (i.e. NR/gbprot/gbnt) or 2. something previously identified by serratus. I am simultaneously aligning to the NR DB to see, for things that are most similar to serratus-identified OTUs, what their closest hit in a public DB is. 

This is when I came across the cases where the closest hit from alignment to `otu_centroids.fa` is `Na` (i.e. the OTU doesn't appear in the `acc_u` file. Is it safe to assume that all of these are cases where the closest hit is something identified by serratus?

Thanks for the responses here, really appreciate it!

**Comment by ababaian** [comment]
We actually have all `sOTU` centroids aligned to GenBank `nr` pre-computed if you want to do this quickly. If you're familiar with `R` it's in the most recent update to `palmID` [web version here](https://serratus.io/palmid), but you can also run it in `R` as a stand-alone.

Here is an example for [Ruche Virus](https://serratus.io/palmid?hash=93aeeec2f5e82c614b71c2ab87dc6eef261b997b).

![image](https://github.com/rcedgar/palmdb/assets/9220907/19d3c405-a57e-49b1-a11e-1b9b59453e36)

---

Alternatively if you're OK with SQL this can be easily accessed with a query:
![image](https://github.com/rcedgar/palmdb/assets/9220907/80773252-e208-47d3-89de-071cc1b195e4)

where `percent_identity` in this table refers to the `sotu` amino acid alignment to GenBank `nr` (as of a couple of months ago). The taxonomy which is given reflects the taxonomy of the top `nr` hit. So `u135511` matches `URG15722.1` at 70% identity.

**Comment by katrinakalantar** [comment]
Thanks @ababaian, super helpful work-around! Is there any information on when the `palm_tax` table was generated? Is the snapshot of `nr` that was used there equivalent to what was used in generating the PalmDB files from `2021-03-14`?

**Comment by ababaian** [comment]
The `palm_tax` table was made on May 1st 2023 (`nr` was taken from that week). So it's not the same as the old version of palmDb.
