### ISSUE TITLE
HCMV missing

### ISSUE THREAD

**Issue by Nusob888** [rcedgar/palmdb#4]
Hi, 

There is probably a very simple answer to this, but I can't seem to find HCMV in the u_tax.tsv? Is this correct?

I've tried a few searches for alternative names

Many thanks for any help

**Comment by ababaian** [comment]
Hi, CMV is a DNA virus, palmDB is a RNA virus RdRp database :)

**Comment by Nusob888** [comment]
Yes, I figured that is the case but noticed other herpesviridae in there, which didnt make sense to me. 

Also, somewhat hopeful question as a recent single-cell tool uses palmdb as a reference for viral transcript alignment.
